services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tcg-mdx-blog
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.blog.entrypoints=https'
      - 'traefik.http.routers.blog.rule=Host(`tcglabs.id`)'
      - 'traefik.http.routers.blog.tls=true'
      - 'traefik.http.services.blog.loadbalancer.server.port=3000'

networks:
  proxy:
    external: true
