services:
  blog:
    context: .
    build: Dockerfile
    container_name: tcg-mdx-blog
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nextjs.entrypoints=https'
      - 'traefik.http.routers.nextjs.rule=Host(`tcglabs.id`)'
      - 'traefik.http.services.nextjs.loadbalancer.server.port=3000'

networks:
  proxy:
    external: true
